/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author LAURA
 */
public class MenuVista extends javax.swing.JFrame {


    public JButton getBtnInstrucciones() {
        return BtnInstrucciones;
    }

    public JButton getBtnPlay() {
        return BtnPlay;
    }


    public JButton getBtnSirve() {
        return BtnSirve;
    }

    public JPanel getPPal() {
        return PPal;
    }

    public void setBtnInstrucciones(JButton BtnInstrucciones) {
        this.BtnInstrucciones = BtnInstrucciones;
    }

    public void setBtnPlay(JButton BtnPlay) {
        this.BtnPlay = BtnPlay;
    }
  
    public void setBtnSiguiente(JButton BtnSiguiente) {
        this.BtnSiguiente = BtnSiguiente;
    }

    public void setBtnSirve(JButton BtnSirve) {
        this.BtnSirve = BtnSirve;
    }

    public void setPPal(JPanel PPal) {
        this.PPal = PPal;
    }

    public void IrAInstrucciones(ActionListener listener){
        getBtnSirve().addActionListener(listener);
        
    }    

    /**
     * Creates new form Menu
     */
    public MenuVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PPal = new javax.swing.JPanel();
        BtnInstrucciones = new javax.swing.JButton();
        BtnPlay = new javax.swing.JButton();
        BtnSiguiente = new javax.swing.JButton();
        BtnSirve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PPal.setFocusable(false);
        PPal.setPreferredSize(new java.awt.Dimension(668, 445));
        PPal.setLayout(null);

        BtnInstrucciones.setContentAreaFilled(false);
        BtnInstrucciones.setFocusable(false);
        BtnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInstruccionesActionPerformed(evt);
            }
        });
        PPal.add(BtnInstrucciones);
        BtnInstrucciones.setBounds(20, 309, 139, 106);

        BtnPlay.setContentAreaFilled(false);
        BtnPlay.setFocusable(false);
        BtnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPlayActionPerformed(evt);
            }
        });
        PPal.add(BtnPlay);
        BtnPlay.setBounds(189, 293, 258, 135);

        BtnSiguiente.setText("Siguiente");
        BtnSiguiente.setContentAreaFilled(false);
        BtnSiguiente.setFocusable(false);
        BtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteActionPerformed(evt);
            }
        });
        PPal.add(BtnSiguiente);
        BtnSiguiente.setBounds(456, 6, 206, 42);

        BtnSirve.setContentAreaFilled(false);
        BtnSirve.setFocusable(false);
        BtnSirve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSirveActionPerformed(evt);
            }
        });
        PPal.add(BtnSirve);
        BtnSirve.setBounds(453, 316, 207, 105);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PPal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PPal, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSirveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSirveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSirveActionPerformed

    private void BtnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPlayActionPerformed

    private void BtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSiguienteActionPerformed

    private void BtnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInstruccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnInstruccionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInstrucciones;
    private javax.swing.JButton BtnPlay;
    private javax.swing.JButton BtnSiguiente;
    private javax.swing.JButton BtnSirve;
    private javax.swing.JPanel PPal;
    // End of variables declaration//GEN-END:variables
}
